[package]
name = "ticket-generator-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = "0.14.2"
qrcode = "0.14.1"
serde = "1.0.219"
tokio = "1.46.1"
axum = "0.7.5"
serde_json = "1.0.117"
image = "0.25.1"
